apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeDisk
metadata:
  name: dev-4-7-storage-metadata-store # {"$kpt-set":"name-storage-metadata-store"}
spec:
  location: asia-east1-c # {"$kpt-set":"location"}
  size: 20
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeDisk
metadata:
  name: dev-4-7-storage-artifact-store # {"$kpt-set":"name-storage-artifact-store"}
spec:
  location: asia-east1-c # {"$kpt-set":"location"}
  size: 200
