apiVersion: v1
data:
  $patch: replace # We do not need some of the original fields.
  admin: gongyuan@kubeflow.org # {"$kpt-set":"email"}
  gcp-sa: dev-4-7-user@gongyuan-dev.iam.gserviceaccount.com # {"$kpt-set":"gcp-sa"}
kind: ConfigMap
metadata:
  name: config
