apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    kustomize.component: profiles
  name: profiles-deployment
  namespace: kubeflow
spec:
  replicas: 1
  selector:
    matchLabels:
      kustomize.component: profiles
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        kustomize.component: profiles
    spec:
      containers:
      - command:
        - /manager
        - -userid-header
        - $(USERID_HEADER)
        - -userid-prefix
        - $(USERID_PREFIX)
        - -workload-identity
        - $(WORKLOAD_IDENTITY)
        env:
        - name: USERID_HEADER
          valueFrom:
            configMapKeyRef:
              key: userid-header
              name: kubeflow-config-h98fkdgb95
        - name: USERID_PREFIX
          valueFrom:
            configMapKeyRef:
              key: userid-prefix
              name: kubeflow-config-h98fkdgb95
        - name: WORKLOAD_IDENTITY
          valueFrom:
            configMapKeyRef:
              key: gcp-sa
              name: profiles-config-k4bf778kb2
        envFrom:
        - configMapRef:
            name: profiles-config-k4bf778kb2
        image: gcr.io/jamxl-kfp-dev/profile-controller:kf-v1.3-rc0
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /metrics
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        name: manager
        ports:
        - containerPort: 8080
          name: manager-http
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/config/labels
          name: namespace-labels
          readOnly: true
      - command:
        - /access-management
        - -cluster-admin
        - $(ADMIN)
        - -userid-header
        - $(USERID_HEADER)
        - -userid-prefix
        - $(USERID_PREFIX)
        env:
        - name: ADMIN
          valueFrom:
            configMapKeyRef:
              key: admin
              name: profiles-config-k4bf778kb2
        - name: USERID_HEADER
          valueFrom:
            configMapKeyRef:
              key: userid-header
              name: kubeflow-config-h98fkdgb95
        - name: USERID_PREFIX
          valueFrom:
            configMapKeyRef:
              key: userid-prefix
              name: kubeflow-config-h98fkdgb95
        - name: WORKLOAD_IDENTITY
          valueFrom:
            configMapKeyRef:
              key: gcp-sa
              name: profiles-config-k4bf778kb2
        envFrom:
        - configMapRef:
            name: profiles-config-k4bf778kb2
        image: public.ecr.aws/j1r0q0g6/notebooks/access-management:v1.3.0-rc.0
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /metrics
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 30
        name: kfam
        ports:
        - containerPort: 8081
          name: kfam-http
          protocol: TCP
      serviceAccountName: profiles-controller-service-account
      volumes:
      - configMap:
          name: namespace-labels-data-mktf728876
        name: namespace-labels
